### ISSUE TITLE
Ghost 使用多说怎么自定义样式? 

### ISSUE THREAD

**Issue by KISSMonX** [duoshuo/duoshuo-embed.css#9]
**ghost 版本 0.6.2 .
目前的问题就是评论框太宽了. 基本占了整屏宽度.  
不知道配置哪个文件, 以前也没学过相关知识.  
[http://stdbit.com/site-function-test/](http://stdbit.com/site-function-test/)**
不知道在哪里问, 就放到这里了.

**Comment by turingou** [comment]
有两种方法可以覆盖原有的评论框样式

1. 审查元素后直接在自己的样式表中用更高权重的样式覆盖多说评论框的样式
2. fork 一份本仓库，然后编辑 less 文件中的变量，或直接修改 less 文件后，生成最终的样式文件，而后添加到自己的网站上，同时，将 `duoshuoQuery.theme` 设置为 `none`

**Comment by KISSMonX** [comment]
好的. 谢谢你.  
开始用的是 Disqus, 也是一样不自动适配, 我看其他人的网站都是大小合适.
现在直接在多说的**后台管理->设置->自定义CSS** 里加入了: 
`#ds-thread {margin:68px;} // 还有其他代码` 
勉强让评论框不那么大了, PC 和 ipad 访问也正常, 就是手机访问的时候评论框不正常.  
我再继续学习吧, 之前没有接触过前端知识.
